# Generated by Django 5.2.7 on 2026-01-28 15:10

import django.db.models.deletion
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(help_text='e.g. https://app.example.com', max_length=2048)),
                ('hostname', models.CharField(blank=True, help_text='Optional display or Host header', max_length=255)),
                ('check_interval_seconds', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_cert_path', models.CharField(blank=True, max_length=1024)),
                ('client_key_path', models.CharField(blank=True, max_length=1024)),
                ('ca_bundle_path', models.CharField(blank=True, max_length=1024)),
                ('expected_status_codes', models.JSONField(blank=True, default=monitor.models.default_expected_status_codes)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('watched_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='monitor.watchedapplication')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['watched_application', '-checked_at'], name='monitor_che_watched_cef986_idx')],
            },
        ),
    ]
