# Generated by Django 5.2.7 on 2026-01-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedapplication',
            name='client_p12_password',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='watchedapplication',
            name='client_p12_path',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
