# Generated by Django 5.2.7 on 2026-01-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_add_client_p12_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedapplication',
            name='alert_down_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchedapplication',
            name='alert_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
